### PR TITLE
Qt advanced

### PR DESCRIPTION
**Pull request by wilsonk**
Hopefully this works ok for you. I moved the smaller example over to qt5demo_simple.d. Let me know if there are any problems.

### CODE REVIEW

**Comment by Syniurge** [comment]
Thanks Kelly, looks good.

Will merge tomorrow, I had little time this w-e and I'm still stuck with some "deep" changes trying to make the emission of functions more hygienic (less invalid decls), so I haven't tried to compile your demo yet.

**Comment by wilsonk** [comment]
Hello Elie, merge when you can...sorry about all the merging commits, I didn't even see that until just now! I guess I should have squashed them? Have I told you I haven't work with Git much :)?

Too bad that the changes for function emission and debug info have to be that deep. I'll try to build this demo once you commit.

I might push the fastflow demos tonight, also, but I might just wait until you push your changes. If you want me to push the fastflow stuff right away, just let me know.

**Comment by Syniurge** [comment]
Merged with f3cd9b82a40e293263e55f6d3bd007f599e30ca6.

**Comment by Syniurge** [comment]
Sorry for the huugge delay Kelly btw :/

I haven't had a working Calypso binary for weeks before the recent commits, if that can count as an excuse.

**Pull request closed without merging**
